### PR TITLE
feat: throw runtime error for dimensional check failures

### PR DESCRIPTION
**Pull request by sanjayankur31**

### CODE REVIEW

**Comment by sanjayankur31** [comment]
All the LEMS examples in the NeuroML2 repo passed, but it'll be good to check if any of our existing models fail because of this (and correct them?).

**Comment by sanjayankur31** [comment]
@pgleeson : just ran into this fall out from the dimensional fixes while re-building the java stack in experimental: `python getNeuroML.py experimental`:

```
(INFO) Added cpt sim1                                                                                                                                                        (INFO) Loaded LEMS: Lems (25 dimensions, 75 units, 9 types, 2 components)                                                                                                    
(INFO) Written to: /home/asinha/Documents/02_Code/00_mine/NeuroML/software/org.neuroml.import/src/test/resources/Simple3Species_LEMS.xml                                     
(INFO) Loading LEMS file from: /home/asinha/Documents/02_Code/00_mine/NeuroML/software/org.neuroml.import/src/test/resources/Simple3Species_LEMS.xml                         
(INFO) Reading from: /home/asinha/Documents/02_Code/00_mine/NeuroML/software/org.neuroml.import/src/test/resources/Simple3Species_LEMS.xml                                   
(LOG)  .......  last warning repeated 30 times                                                                                                                               
[ERROR] Tests run: 6, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.245 s <<< FAILURE! -- in org.neuroml.importer.test.SBMLImporterTest                                
[ERROR] org.neuroml.importer.test.SBMLImporterTest.testIzhikevich -- Time elapsed: 0.034 s <<< ERROR!                                                                        
org.lemsml.jlems.core.expression.ParseError:                                                                                                                                 
Error checking equations of ComponentType: ComponentType, name=Izhikevicha (none)                                                                                            
b (none)                                                                                                                                                                     
c (none)                                                                                                                                                                     
d (none)                                                                                                                                                                     
Vthresh (none)                                                                                                                                                               
i_amp (none)                                                                                                                                                                 i_del (none)                                                                                                                                                                 tscale (per_time)  = 1per_s                                                                                                                                                  
cell (none)  = 1.0                                                                                                                                                           
                                                                                                                                                                             
(Dimension mismatch in the equation: time = 1. Residual dimension: ExprDimensional[t=1]                                                                                      
Dimension of time: Dimension[none dimensionless], multiplier=Dimension[per_time t=-1], left=Dimension[ t=-1], rhs=ExprDimensional[dimensionless]                             
All:{vv=Dimension[none dimensionless], a=Dimension[none dimensionless], i_del=Dimension[none dimensionless], b=Dimension[none dimensionless], c=Dimension[none dimensionless]
, tscale=Dimension[per_time t=-1], d=Dimension[none dimensionless], i=Dimension[none dimensionless], Vthresh=Dimension[none dimensionless], cell=Dimension[none dimensionless
], t=ExprDimensional[t=1], U=Dimension[none dimensionless], i_amp=Dimension[none dimensionless], time=Dimension[none dimensionless]})                 
```

Still debugging to see what's causing it.

**Comment by sanjayankur31** [comment]
Here's the LEMS file that is generated that it doesn't like:

[Izhikevich_LEMS.xml.txt](https://github.com/user-attachments/files/15840376/Izhikevich_LEMS.xml.txt)

**Comment by sanjayankur31** [comment]
This is the dynamics block:

```
        <Dynamics simultaneous="false">
            <StateVariable name="i" dimension="none" exposure="i"/>
            <StateVariable name="vv" dimension="none" exposure="vv"/>
            <StateVariable name="U" dimension="none" exposure="U"/>
            <StateVariable name="time" dimension="none"/>
            <TimeDerivative variable="i" value="tscale * 0"/>
            <TimeDerivative variable="vv" value="tscale * ((((((0.04 * (vv ^ 2.0)) + (5.0 * vv)) + 140.0) - U) + i))"/>
            <TimeDerivative variable="U" value="tscale * ((a * ((b * vv) - U)))"/>
            <TimeDerivative variable="time" value="1"/>
            <OnStart>
                <StateAssignment variable="i" value="0.0"/>
                <StateAssignment variable="vv" value="-70.0"/>
                <StateAssignment variable="U" value="-14.0"/>
            </OnStart>
            <OnCondition test="vv .gt. Vthresh">
                <StateAssignment variable="vv" value="c"/>
                <StateAssignment variable="U" value="(U + d)"/>
            </OnCondition>
            <OnCondition test="(t * tscale)  .gt. i_del">
                <StateAssignment variable="i" value="i_amp"/>
            </OnCondition>
        </Dynamics>
        <Constant name="tscale" value="1per_s" dimension="per_time"/>
        <Constant name="cell" value="1.0" dimension="none"/>
```

the error is pointing to this line:

```
            <TimeDerivative variable="time" value="1"/>

```

I think the RHS needs to be `value = "tscale * 1"` perhaps?

**Comment by pgleeson** [comment]
@sanjayankur31 Yes, probably that's the issue. Note the age of those files though, they predate the sbml showcase and probably izh in nml2... If it's a quick fix then fix it, otherwise they're not needed...

**Pull request merged**
